Repository Badger-Finance/badger-rewards, pull requests merged in 2022-01, with the labels that each got.

#434 release: nft boost
  .deploy/stg/.app.yaml
  .github/workflows/deploy_stg.yaml
  abis/eth/NFTControl.json
  helpers/constants.py
  helpers/enums.py
  integration_tests/test_boost_workflow.py
  rewards/aws/boost.py
  rewards/boost/boost_utils.py
  rewards/boost/calc_boost.py
  rewards/classes/NftWeightSchedule.py
  rewards/snapshot/chain_snapshot.py
  rewards/snapshot/claims_snapshot.py
  rewards/snapshot/nft_snapshot.py
  rewards/utils/emission_utils.py
  rewards/utils/tx_utils.py
  subgraph/config.py
  subgraph/queries/nfts.py
  subgraph/subgraph_utils.py
  tests/conftest.py
  tests/test_boost/__init__.py
  tests/test_boost/test_boost.py
  tests/test_boost/test_calc_boost.py
  tests/test_calc_boost.py
  tests/test_cycles/__init__.py
  tests/test_cycles/test_cycles_arb.py
  tests/test_cycles/test_cycles_eth.py
  tests/test_cycles/test_cycles_poly.py
  tests/test_managers/__init__.py
  tests/test_managers/test_rewards_manager.py
  tests/test_managers/test_tree_manager.py
  tests/test_snapshots/__init__.py
  tests/test_snapshots/test_chain_snapshots.py
  tests/test_snapshots/test_claims_snapshot.py
  tests/test_snapshots/test_nft_snapshot.py
  tests/test_utils/__init__.py
  tests/test_utils/cycle_utils.py
  tests/test_utils/test_boost_utils.py
  tests/test_utils/test_emission_utils.py
  tests/test_utils/test_env_config.py
  tests/test_utils/test_http_client.py
  tests/test_utils/test_http_requests_functions.py
  tests/test_utils/test_subgraph_utils.py
  tests/test_utils/test_tree_utils.py
  tests/test_utils/test_tx_utils.py
  tests/utils.py
Labels: ON HODL

#447 chore: increase gql log level to WARNING
  subgraph/subgraph_utils.py
Labels: enhancement

#440 feat: improve discord logging for rewards manager calculate sett rewards
  rewards/classes/RewardsManager.py
  tests/test_managers/test_rewards_manager.py
Labels: enhancement

#422 Unclaimed rewards snapshot
  badger_api/claimable.py
  badger_api/requests.py
  helpers/http_client.py
  integration_tests/test_boost_workflow.py
  requirements-dev.txt
  rewards/aws/boost.py
  rewards/aws/helpers.py
  rewards/aws/trees.py
  rewards/boost/boost_utils.py
  rewards/boost/calc_boost.py
  rewards/calc_rewards.py
  rewards/classes/MerkleTree.py
  rewards/classes/RewardsManager.py
  rewards/emission_handlers.py
  rewards/rewards_checker.py
  rewards/snapshot/chain_snapshot.py
  rewards/snapshot/claims_snapshot.py
  rewards/utils/emission_utils.py
  rewards/utils/tree_utils.py
  rewards/utils/tx_utils.py
  scripts/rewards/eth/approve_eth.py
  scripts/rewards/eth/custom_propose_eth.py
  scripts/rewards/eth_retroactive/approve.py
  scripts/rewards/eth_retroactive/calc_negative_balances.py
  scripts/rewards/eth_retroactive/propose.py
  scripts/rewards/eth_retroactive/retro.py
  scripts/rewards/fix_cycle/fix_eth_approve.py
  scripts/rewards/ibbtc_rewards/approve.py
  scripts/rewards/ibbtc_rewards/move_ibbtc.py
  subgraph/config.py
  subgraph/queries/harvests.py
  subgraph/queries/nfts.py
  subgraph/queries/setts.py
  subgraph/queries/tokens.py
  tests/conftest.py
  tests/test_boost/test_calc_boost.py
  tests/test_claimable.py
  tests/test_cycles/test_cycles_arb.py
  tests/test_cycles/test_cycles_eth.py
  tests/test_cycles/test_cycles_poly.py
  tests/test_managers/test_rewards_manager.py
  tests/test_snapshots/test_chain_snapshots.py
  tests/test_snapshots/test_claims_snapshot.py
  tests/test_utils/cycle_utils.py
  tests/test_utils/test_boost_utils.py
  tests/test_utils/test_emission_utils.py
  tests/test_utils/test_http_client.py
  tests/test_utils/test_http_requests_functions.py
  tests/test_utils/test_tree_utils.py
  tests/test_utils/test_tx_utils.py
  tests/utils.py
Labels: ON HODL

#481 Redirect ibbtc rewards
  helpers/constants.py
  rewards/classes/RewardsManager.py
  rewards/emission_handlers.py
  rewards/utils/rewards_utils.py
Labels: ON HODL

#557 feat: add rem badger to native list
  helpers/constants.py
Labels: ON HODL

#559 Fix number of taken snapshots to N-1
  helpers/constants.py
  rewards/classes/RewardsManager.py
  rewards/snapshot/chain_snapshot.py
  tests/test_snapshots/test_chain_snapshots.py
Labels: bug, TWAP
